config/routes.rb
      patch :types

      get 'column_sums', controller: 'work_packages'

      # Destroy uses a get request to prompt the user before the actual DELETE request
      get :destroy_info, as: 'confirm_destroy'
    end

    collection do
      get :level_list
    end

    resource :time_entry_activities, controller: 'projects/time_entry_activities', only: %i[update]

    resources :versions, only: %i[new create] do
      collection do
        put :close_completed
      end
    end

    # this is only another name for versions#index
    # For nice "road in the url for the index action
    # this could probably be rewritten with a resource as: 'roadmap'
    match '/roadmap' => 'versions#index', via: :get

    resources :news, only: %i[index new create]

    # Match everything to be the ID of the wiki page except the part that
    # is reserved for the format. This assumes that we have only two formats:
    # .txt and .html
    resources :wiki,
              constraints: { id: /([^\/]+(?=\.markdown)|[^\/]+)/ },
              except: %i[index create] do
      collection do
        post '/new' => 'wiki#create', as: 'create'
        get :export
        get :date_index
        get '/index' => 'wiki#index'
      end

      member do
        get '/new' => 'wiki#new_child', as: 'new_child'
        get '/diff/:version/vs/:version_from' => 'wiki#diff', as: 'wiki_diff_compare'
        get '/diff(/:version)' => 'wiki#diff', as: 'wiki_diff'
        get '/annotate/:version' => 'wiki#annotate', as: 'wiki_annotate'
        get '/toc' => 'wiki#index'
        match :rename, via: %i[get patch]
        get :parent_page, action: 'edit_parent_page'
        patch :parent_page, action: 'update_parent_page'
        get :history
        post :protect
        get :select_main_menu_item, to: 'wiki_menu_items#select_main_menu_item'
        post :replace_main_menu_item, to: 'wiki_menu_items#replace_main_menu_item'
      end
    end

    # as routes for index and show are swapped
    # it is necessary to define the show action later
    # than any other route as it otherwise would
    # work as a catchall for everything under /wiki
    get 'wiki' => 'wiki#show'

    namespace :work_packages do
      resources :calendar, controller: 'calendars', only: [:index]
    end

    resources :work_packages, only: [] do
      collection do
        get '/report/:detail' => 'work_packages/reports#report_details'
        get '/report' => 'work_packages/reports#report'
      end

      # states managed by client-side routing on work_package#index
      get '(/*state)' => 'work_packages#index', on: :collection, as: ''
      get '/create_new' => 'work_packages#index', on: :collection, as: 'new_split'
      get '/new' => 'work_packages#index', on: :collection, as: 'new'

      # state for show view in project context
      get '(/*state)' => 'work_packages#show', on: :member, as: ''
    end

    resources :activity, :activities, only: :index, controller: 'activities'

    resources :forums do
      member do
        get :confirm_destroy
        get :move
        post :move
      end
    end

    resources :categories, except: %i[index show], shallow: true

    resources :members, only: %i[index create update destroy], shallow: true do
      collection do
        match :autocomplete_for_member, via: %i[get]
      end
    end

    resource :repository, controller: 'repositories', except: [:new] do
      # Destroy uses a get request to prompt the user before the actual DELETE request
      get :destroy_info
      get :committers
      post :committers
      get :graph
      get :revisions

      get '/statistics', action: :stats, as: 'stats'

      get '(/revisions/:rev)/diff.:format', action: :diff
      get '(/revisions/:rev)/diff(/*repo_path)',
          action: :diff,
          format: 'html',
          constraints: { rev: /[\w0-9\.\-_]+/, repo_path: /.*/ }

      get '(/revisions/:rev)/:format/*repo_path',
          action: :entry,
          format: /raw/,
          rev: /[\w0-9\.\-_]+/

      %w{diff annotate changes entry browse}.each do |action|
        get "(/revisions/:rev)/#{action}(/*repo_path)",
            format: 'html',
            action: action,
            constraints: { rev: /[\w0-9\.\-_]+/, repo_path: /.*/ },
            as: "#{action}_revision"
      end

      get '/revision(/:rev)', rev: /[\w0-9\.\-_]+/,
                              action: :revision,
                              as: 'show_revision'

      get '(/revisions/:rev)(/*repo_path)',
          action: :show,
          format: 'html',
          constraints: { rev: /[\w0-9\.\-_]+/, repo_path: /.*/ },
          as: 'show_revisions_path'
    end
  end

  resources :admin, controller: :admin, only: :index do
    collection do
      get :plugins
      get :info
      post :force_user_language
      post :test_email
    end
  end

  scope 'admin' do
    resource :announcements, only: %i[edit update]
    constraints(Enterprise) do
      resource :enterprise, only: %i[show create destroy]
      scope controller: 'enterprises' do
        post 'enterprise/save_trial_key' => 'enterprises#save_trial_key'
        delete 'enterprise/delete_trial_key' => 'enterprises#delete_trial_key'
      end
    end
    resources :enumerations

    delete 'design/logo' => 'custom_styles#logo_delete', as: 'custom_style_logo_delete'
    delete 'design/favicon' => 'custom_styles#favicon_delete', as: 'custom_style_favicon_delete'
    delete 'design/touch_icon' => 'custom_styles#touch_icon_delete', as: 'custom_style_touch_icon_delete'
    get 'design/upsale' => 'custom_styles#upsale', as: 'custom_style_upsale'
    post 'design/colors' => 'custom_styles#update_colors', as: 'update_design_colors'
    post 'design/themes' => 'custom_styles#update_themes', as: 'update_design_themes'
    resource :custom_style, only: %i[update show create], path: 'design'

    resources :attribute_help_texts, only: %i(index new create edit update destroy)

    resources :groups do
      member do
        # this should be put into it's own resource
        match '/members' => 'groups#add_users', via: :post, as: 'members_of'
        match '/members/:user_id' => 'groups#remove_user', via: :delete, as: 'member_of'
        # this should be put into it's own resource
        match '/memberships/:membership_id' => 'groups#edit_membership', via: :put, as: 'membership_of'
        match '/memberships/:membership_id' => 'groups#destroy_membership', via: :delete
        match '/memberships' => 'groups#create_memberships', via: :post, as: 'memberships_of'
      end
    end

    resources :roles, except: %i[show] do
      collection do
        put '/' => 'roles#bulk_update'
        get :report
      end
    end

    resources :auth_sources, :ldap_auth_sources do
      member do
        get :test_connection
      end
    end

    resources :custom_actions, except: :show

    namespace :oauth do
      resources :applications
    end
  end

  namespace :admin do
    resource :incoming_mails, only: %i[show update]
    resource :mail_notifications, only: %i[show update]
  end

  resource :settings, only: %i(update show) do
    SettingsHelper.system_settings_tabs.each do |tab|
      get tab[:name], controller: "settings/#{tab[:name]}", action: 'show', as: "#{tab[:name]}"
      patch tab[:name], controller: "settings/#{tab[:name]}", action: 'update', as: "update_#{tab[:name]}"
    end

    # We should fix this crappy routing (split up and rename controller methods)
    collection do
      match 'plugin/:id', action: 'plugin', via: %i[get post]
    end
  end

  resource :workflows, only: %i[edit update show] do
    member do
      # We should fix this crappy routing (split up and rename controller methods)
      match 'copy', action: 'copy', via: %i[get post]
    end
  end

  namespace :work_packages do
    match 'auto_complete' => 'auto_completes#index', via: %i[get post]
    resources :calendar, controller: 'calendars', only: [:index]
    resource :bulk, controller: 'bulk', only: %i[edit update destroy]
    # FIXME: this is kind of evil!! We need to remove this soonest and
    # cover the functionality. Route is being used in work-package-service.js:331
    get '/bulk' => 'bulk#destroy'
  end

  scope controller: 'work_packages/settings' do
    get 'work_package_tracking' => 'work_packages/settings#index'
    post 'work_package_tracking' => 'work_packages/settings#edit'
  end

  resources :work_packages, only: [:index] do
    # move bulk of wps
    get 'move/new' => 'work_packages/moves#new', on: :collection, as: 'new_move'
    post 'move' => 'work_packages/moves#create', on: :collection, as: 'move'
    # move individual wp
    resource :move, controller: 'work_packages/moves', only: %i[new create]

    # states managed by client-side routing on work_package#index
    get 'details/*state' => 'work_packages#index', on: :collection, as: :details

    # states managed by client-side (angular) routing on work_package#show
    get '/' => 'work_packages#index', on: :collection, as: 'index'
    get '/create_new' => 'work_packages#index', on: :collection, as: 'new_split'
    get '/new' => 'work_packages#index', on: :collection, as: 'new', state: 'new'
    # We do not want to match the work package export routes
    get '(/*state)' => 'work_packages#show', on: :member, as: '', constraints: { id: /\d+/ }
    get '/edit' => 'work_packages#show', on: :member, as: 'edit'
  end

  resources :versions, only: %i[show edit update destroy] do
    member do
      get :status_by
    end
  end

  resources :activity, :activities, only: :index, controller: 'activities'

  resources :users do
    resources :memberships, controller: 'users/memberships', only: %i[update create destroy]

    member do
      match '/edit/:tab' => 'users#edit', via: :get, as: 'tab_edit'
      match '/change_status/:change_action' => 'users#change_status_info', via: :get, as: 'change_status_info'
      post :change_status
      post :resend_invitation
      get :deletion_info
    end
  end

app/controllers/project_settings/repository_controller.rb
#-- encoding: UTF-8
#-- copyright
# OpenProject is an open source project management software.
# Copyright (C) 2012-2020 the OpenProject GmbH
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License version 3.
#
# OpenProject is a fork of ChiliProject, which is a fork of Redmine. The copyright follows:
# Copyright (C) 2006-2017 Jean-Philippe Lang
# Copyright (C) 2010-2013 the ChiliProject Team
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#
# See docs/COPYRIGHT.rdoc for more details.
#++

class ProjectSettings::RepositoryController < ProjectSettingsController
  menu_item :settings_repository

  def show
    @repository = @project.repository || new_repository
    render template: 'repositories/project_settings'
  end

  private

  def new_repository
    return unless params[:scm_vendor]

    service = SCM::RepositoryFactoryService.new(@project, params)
    if service.build_temporary
      @repository = service.repository
    else
      logger.error("Cannot create repository for #{params[:scm_vendor]}")
      flash[:error] = service.build_error
      nil
    end
  end
end

app/controllers/settings/repositories_controller.rb
#-- encoding: UTF-8
#-- copyright
# OpenProject is an open source project management software.
# Copyright (C) 2012-2020 the OpenProject GmbH
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License version 3.
#
# OpenProject is a fork of ChiliProject, which is a fork of Redmine. The copyright follows:
# Copyright (C) 2006-2017 Jean-Philippe Lang
# Copyright (C) 2010-2013 the ChiliProject Team
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#
# See docs/COPYRIGHT.rdoc for more details.
#++

class Settings::RepositoriesController < SettingsController
  include AdminSettingsUpdater

  menu_item :settings_repositories

  def show
    render template: 'settings/_repositories'
  end

  def default_breadcrumb
    t(:label_repository_plural)
  end
end

app/views/repositories/_breadcrumbs.html.erb
<%#-- copyright
OpenProject is an open source project management software.
Copyright (C) 2012-2020 the OpenProject GmbH

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License version 3.

OpenProject is a fork of ChiliProject, which is a fork of Redmine. The copyright follows:
Copyright (C) 2006-2017 Jean-Philippe Lang
Copyright (C) 2010-2013 the ChiliProject Team

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

See docs/COPYRIGHT.rdoc for more details.

++#%>

<%= link_to({ action: 'show', project_id: @project, repo_path: nil, rev: @rev },
            { title: I18n.t(:label_repository_root) }) do %>
  <%= op_icon('icon-home repository-breadcrumbs--home') %>
<% end %>
<%
dirs = path.split('/')
link_path = ''
dirs.each_with_index do |dir, index|
    next if dir.blank?
    link_path << '/' unless link_path.empty?
    link_path << "#{dir}"
    %>
    <span class="repository-breadcrumbs--sep"></span>
      <% if index == dirs.size - 1 %>
        <strong><%= h(dir) %></strong>
      <% else %>
        <%= link_to h(dir), action: 'show', project_id: @project,
                            path: to_path_param(link_path), rev: @rev %>
      <% end %>
<% end %>
<%
  # @rev is revsion or git branch or tag.
  rev_text = @changeset.nil? ? @rev : format_revision(@changeset)
%>
<span class="repository-bradcrumbs--identifier">
  <%= "(#{t('repositories.at_identifier', identifier: rev_text)})" if rev_text.present? %>
</span>

<% html_title(h(with_leading_slash(path))) -%>

app/views/repositories/_checkout_instructions.html.erb
<%#-- copyright
OpenProject is an open source project management software.
Copyright (C) 2012-2020 the OpenProject GmbH

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License version 3.

OpenProject is a fork of ChiliProject, which is a fork of Redmine. The copyright follows:
Copyright (C) 2006-2017 Jean-Philippe Lang
Copyright (C) 2010-2013 the ChiliProject Team

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

See docs/COPYRIGHT.rdoc for more details.

++#%>
<% if @instructions.available? %>
<div id="repository--checkout-instructions"
     class="notification-box -info persistent-toggle--notification"
     hidden>
  <a title="{{ ::I18n.t('js.close_popup_title') }}"
     class="notification-box--close icon-context icon-close">
  </a>
  <div class="notification-box--content">
    <p>
    <%= simple_format instructions.instructions %>
    <% if instructions.manages_permissions? %>
      <br/>
      <span><%= t('repositories.checkout.access_permission') %>:</span>
      <strong><%= t("repositories.checkout.access.#{instructions.permission}") %></strong>
    <% end %>
    </p>
  </div>
</div>
<% elsif @instructions.supported_but_not_enabled? %>
<div class="notification-box -warning">
  <a title="{{ ::I18n.t('js.close_popup_title') }}"
     class="notification-box--close icon-context icon-close">
  </a>
  <div class="notification-box--content">
    <p><%= t('repositories.checkout.not_available') %></p>
  </div>
</div>
<% end %>

app/views/repositories/_dir_list.html.erb
<%#-- copyright
OpenProject is an open source project management software.
Copyright (C) 2012-2020 the OpenProject GmbH

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License version 3.

OpenProject is a fork of ChiliProject, which is a fork of Redmine. The copyright follows:
Copyright (C) 2006-2017 Jean-Philippe Lang
Copyright (C) 2010-2013 the ChiliProject Team

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

See docs/COPYRIGHT.rdoc for more details.

++#%>
<div class="generic-table--container">
  <div class="generic-table--results-container">
    <table class="generic-table" id="browser">
      <colgroup>
        <col highlight-col>
        <col>
        <col highlight-col>
        <col highlight-col>
        <col highlight-col>
        <col highlight-col>
        <col highlight-col>
      </colgroup>
      <thead>
        <tr id="root">
          <th>
            <div class="generic-table--sort-header-outer">
              <div class="generic-table--sort-header">
                <span>
                  <%= Attachment.human_attribute_name(:filename) %>
                </span>
              </div>
            </div>
          </th>
          <th class="hidden-for-sighted">
            <div class="generic-table--sort-header-outer">
              <div class="generic-table--sort-header">
                <span>
                  <%= I18n.t('js.tl_toolbar.outlines') %>
                </span>
              </div>
            </div>
          </th>
          <th>
            <div class="generic-table--sort-header-outer">
              <div class="generic-table--sort-header">
                <span>
                  <%= Attachment.human_attribute_name(:filesize) %>
                </span>
              </div>
            </div>
          </th>
          <th>
            <div class="generic-table--sort-header-outer">
              <div class="generic-table--sort-header">
                <span>
                  <%= t(:label_revision) %>
                </span>
              </div>
            </div>
          </th>
          <th>
            <div class="generic-table--sort-header-outer">
              <div class="generic-table--sort-header">
                <span>
                  <%= t(:label_age) %>
                </span>
              </div>
            </div>
          </th>
          <th>
            <div class="generic-table--sort-header-outer">
              <div class="generic-table--sort-header">
                <span>
                  <%= Changeset.human_attribute_name(:author) %>
                </span>
              </div>
            </div>
          </th>
          <th>
            <div class="generic-table--sort-header-outer">
              <div class="generic-table--sort-header">
                <span>
                  <%= Changeset.human_attribute_name(:comments) %>
                </span>
              </div>
            </div>
          </th>
        </tr>
      </thead>
      <tbody>
        <%= render partial: 'dir_list_content' %>
      </tbody>
    </table>
  </div>
</div>

app/views/repositories/_repository_header.html.erb
<%#-- copyright
OpenProject is an open source project management software.
Copyright (C) 2012-2020 the OpenProject GmbH

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License version 3.

OpenProject is a fork of ChiliProject, which is a fork of Redmine. The copyright follows:
Copyright (C) 2006-2017 Jean-Philippe Lang
Copyright (C) 2010-2013 the ChiliProject Team

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

See docs/COPYRIGHT.rdoc for more details.

++#%>

<% content_for :header_tags do %>
  <meta name="required_script" content="repository_navigation" />
<% end %>

<persistent-toggle data-identifier="repository.checkout_instructions"></persistent-toggle>
<%= toolbar title: t('repositories.named_repository',
                     vendor_name: @repository.class.vendor_name) do %>
  <% if @instructions && @instructions.available? %>
  <li class="toolbar-item toolbar-input-group hidden-for-mobile">
    <div class="toolbar-input-group--affix -prepend">
      <span><%= @instructions.checkout_command %></span>
    </div>
    <input id="repository-checkout-url"
           type="text" class="-clickable" size="40"
           value="<%= @instructions.checkout_url(true) %>"
           readonly>
    <% csp_onclick('this.focus(); this.select();', '#repository-checkout-url') %>
    <copy-to-clipboard click-target=".repository-checkout-copy-button"
                       clipboard-target="#repository-checkout-url">
    </copy-to-clipboard>
    <button class="repository-checkout-copy-button toolbar-input--affix toolbar-input-group--affix -append"
            title="<%= t(:label_copy_to_clipboard) %>">
      <%= op_icon('icon-copy') %>
      <span class="hidden-for-sighted"><%= t(:label_copy_to_clipboard) %></span>
    </button>
  </li>
  <li class="toolbar-item -icon-only">
    <a id="repository--checkout-instructions-toggle"
       class="persistent-toggle--click-handler button"
       title="<%= t('repositories.checkout.show_instructions') %>">
      <%= op_icon('button--icon icon-info1') %>
    </a>
  </li>
  <% end %>
  <% if !empty && User.current.allowed_to?(:browse_repository, @project) %>
  <li class="toolbar-item -icon-only">
    <%= link_to stats_project_repository_path(@project),
        class: 'button', title: t(:label_statistics) do %>
      <%= op_icon('button--icon icon-chart1') %>
    <% end %>
  </li>
  <% end %>
  <%= call_hook(:repositories_navigation_toolbar,
                { repository: @repository, project: @project, repository_empty: empty }) %>
  <% if User.current.allowed_to?(:manage_repository, @project) %>
    <li class="toolbar-item -icon-only">
      <%= link_to settings_repository_project_path(@project),
          class: 'button', title: t(:label_setting_plural) do %>
        <%= op_icon('button--icon icon-settings') %>
      <% end %>
    </li>
  <% end %>
<% end %>


<% if @instructions %>
  <%= render partial: 'checkout_instructions',
             locals: { repository: @repository, instructions: @instructions } %>
<% end %>

app/views/repositories/show.html.erb
<%#-- copyright
OpenProject is an open source project management software.
Copyright (C) 2012-2020 the OpenProject GmbH

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License version 3.

OpenProject is a fork of ChiliProject, which is a fork of Redmine. The copyright follows:
Copyright (C) 2006-2017 Jean-Philippe Lang
Copyright (C) 2010-2013 the ChiliProject Team

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

See docs/COPYRIGHT.rdoc for more details.

++#%>

<%= render partial: 'repository_header', locals: { empty: false } %>

<div class="repository-breadcrumbs">
  <%= render partial: 'breadcrumbs',
             locals: { path: @path, revision: @rev }.merge(kind: 'dir') %>
</div>

<% if !@entries.nil? && authorize_for('repositories', 'browse') %>
<%= render partial: 'dir_list' %>
<% end %>

<%= render_properties(@properties) %>

<%= toolbar title: t(:label_revision_plural), html: { class: 'repository--revision-toolbar' } do %>
  <%# rev => nil prevents overwriting the rev parameter queried for in the form with the parameter from the request %>
  <%= form_tag({ action: controller.action_name,
                 project_id: @project,
                 path: to_path_param(@path),
                 rev: nil
               },
               method: :get,
               id: 'revision_selector',
               class: 'form -vertical'
              ) do %>
    <li class="toolbar-item toolbar-input-group hidden-for-mobile">
      <div>
        <%= label_tag 'rev', I18n.t('repositories.go_to_revision') %>
      </div>
      <%= text_field_tag :rev, @rev, id: 'revision-identifier-input', placeholder: t(:label_revision) %>
    </li>
    <% if !@repository.branches.nil? && @repository.branches.length > 0 %>
    <li class="toolbar-item toolbar-input-group hidden-for-mobile">
      <div>
        <%= label_tag 'branch', I18n.t(:label_branch) %>
      </div>
      <%= select_tag :branch,
                     options_for_select(@repository.branches, @rev),
                     include_blank: "--- #{t(:actionview_instancetag_blank_option)} ---",
                     id: 'revision-branch-select' %>
    </li>
    <% end %>
    <% if !@repository.tags.nil? && @repository.tags.length > 0 %>
    <li class="toolbar-item toolbar-input-group hidden-for-mobile">
      <div>
        <%= label_tag 'tag', I18n.t(:label_tag) %>
      </div>
      <%= select_tag :tag,
                     options_for_select(@repository.tags, @rev),
                     include_blank: "--- #{t(:actionview_instancetag_blank_option)} ---",
                     id: 'revision-tag-select' %>
    </li>
    <% end %>
    <li class="toolbar-item -icon-only">
      <%= link_to({ url: { action: 'revisions', project_id: @project,
                           key: User.current.rss_key } },
                  { class: 'button', title: t('repositories.atom_revision_feed') }) do %>
        <%= op_icon('button--icon icon-export-atom') %>
      <% end %>
    </li>
  <% end %>
<% end %>

<% if authorize_for('repositories', 'revisions') %>
<%   if @changesets && !@changesets.empty? %>
<%=    render partial: 'revisions',
              locals: {project: @project, path: @path,
                          revisions: @changesets, entry: nil }%>
<%   end %>
<p>
<%
     has_branches = (!@repository.branches.nil? && @repository.branches.length > 0)
     sep = ''
 %>

<%   if @repository.supports_all_revisions? && @path.blank? %>
<%= link_to t(:label_view_all_revisions), revisions_project_repository_path(@project) %>
<%   sep = '|' %>
<%   end %>
</p>
<% end %>

<% html_title(t(:label_repository)) -%>